### ISSUE TITLE
Alt commit action

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/codemeta2cff#1]
If we still have issues with the commit action, switch to

```
      - name: Commit and Push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Add CITATION.cff for release'
          file_pattern: 'CITATION.cff'
```
